export * from "./types.js";
export * from "./stats.js";
export * from "./tukey.js";
export * from "./pressupostos.js";
export * from "./comparacao.js";
export * from "./anova.js";
export * from "./splitPlot.js";
export * from "./factorial.js";
export * from "./transform.js";
